version: '2'
services:
  app:
    build: .
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:pass@mysql:3306
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3000:3000'
      - '50022:22'
    volumes:
      - .:/usr/src/momonga
    links:
      - mysql
  mysql:
    image: "mysql:8.0.4"
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-confd:/etc/mysql/conf.d
  webpacker:
    build: .
    command: ./bin/webpack-dev-server
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACK_DEV_SERVER_HOST: 0.0.0.0
      WEBPACK_DEV_SERVER_PUBLIC: 0.0.0.0:3035
    volumes:
      - .:/usr/src/momonga
      - ./node_modules:/usr/src/momonga/node_modules
    ports:
      - '3035:3035'
volumes:
  mysql-data:
    driver: local
